# Generated by Django 3.0.2 on 2020-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='std',
            field=models.IntegerField(),
        ),
    ]
